//----------------------------------------------------------------------------------------------------------------------
//	WinUIToolbox.idl			©2023 Stevo Brock		All rights reserved.
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
// MARK: WinUIToolbox namespace
namespace WinUIToolbox {

	//------------------------------------------------------------------------------------------------------------------
	// Delegates
	delegate	void	ContentDialogHandler(Object sender, Microsoft.UI.Xaml.Controls.ContentDialog contentDialog);
}
