//----------------------------------------------------------------------------------------------------------------------
//	DropTargetControl.idl			©2023 Stevo Brock		All rights reserved.
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
// MARK: WinRTToolbox namespace
namespace WinRTToolbox {

	//------------------------------------------------------------------------------------------------------------------
	// MARK: DropTargetControl
	[default_interface]
	runtimeclass DropTargetControl : Microsoft.UI.Xaml.Controls.UserControl {
		// Methods
		DropTargetControl();
	}
}
