//----------------------------------------------------------------------------------------------------------------------
//	DropTargetView.idl			©2023 Stevo Brock		All rights reserved.
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
// MARK: WinUIToolbox namespace
namespace WinUIToolbox {

	//------------------------------------------------------------------------------------------------------------------
	// MARK: DropTargetView
	[default_interface]
	runtimeclass DropTargetView : Microsoft.UI.Xaml.Controls.UserControl {
		// Methods
		DropTargetView();

		// Events
		event	Windows.Foundation.EventHandler<Windows.Foundation.Collections.IVectorView<Windows.Storage.IStorageItem> >	StorageItemsEvent;
	}
}
