//----------------------------------------------------------------------------------------------------------------------
//	DropTargetView.idl			©2023 Stevo Brock		All rights reserved.
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
// MARK: WinUIToolbox namespace
namespace WinUIToolbox {

	//------------------------------------------------------------------------------------------------------------------
	// MARK: DropTargetView
	[default_interface]
	runtimeclass DropTargetView : Microsoft.UI.Xaml.Controls.UserControl {
																							// Lifecycle Methods
																							DropTargetView();

																							// Events
		event	Windows.Foundation.EventHandler<IVectorView<Windows.Storage.IStorageItem> >	StorageItemsEvent;

																							// Properties
				Int32																		DragAndDropPriority;
	}
}
